"""v2-refactor

Revision ID: dadaeb0b9da7
Revises: 
Create Date: 2026-05-13 22:30:06.447850
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dadaeb0b9da7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_type',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('employee',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('work_type', sa.String(length=50), nullable=False),
    sa.Column('personnel_type', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('daily_wage', sa.Float(), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_code')
    )
    op.create_table('work_type',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('project',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('region_province', sa.String(length=50), nullable=True),
    sa.Column('region_city', sa.String(length=50), nullable=True),
    sa.Column('party_a', sa.String(length=200), nullable=True),
    sa.Column('party_b', sa.String(length=200), nullable=True),
    sa.Column('contact_person', sa.String(length=50), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('fund_source', sa.String(length=30), nullable=True),
    sa.Column('project_nature', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('manager_id', sa.String(length=36), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_code')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('budget_item',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('sub_category', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('work_days', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('is_personnel', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('construction_task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('task_name', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('contract_amount', sa.Float(), nullable=False),
    sa.Column('discount_rate', sa.Float(), nullable=False),
    sa.Column('actual_amount', sa.Float(), nullable=False),
    sa.Column('sign_date', sa.Date(), nullable=True),
    sa.Column('drafter', sa.String(length=50), nullable=True),
    sa.Column('reviewer', sa.String(length=50), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('daily_execution',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('seq_number', sa.Integer(), nullable=False),
    sa.Column('subcontract_fee', sa.Float(), nullable=False),
    sa.Column('inhouse_personnel', sa.Float(), nullable=False),
    sa.Column('enterprise_personnel', sa.Float(), nullable=False),
    sa.Column('dispatched_personnel', sa.Float(), nullable=False),
    sa.Column('relevant_fee', sa.Float(), nullable=False),
    sa.Column('material_fee', sa.Float(), nullable=False),
    sa.Column('labor_fee', sa.Float(), nullable=False),
    sa.Column('rental_fee', sa.Float(), nullable=False),
    sa.Column('transport_fee', sa.Float(), nullable=False),
    sa.Column('office_fee', sa.Float(), nullable=False),
    sa.Column('entertainment_fee', sa.Float(), nullable=False),
    sa.Column('other_fee', sa.Float(), nullable=False),
    sa.Column('travel_fee', sa.Float(), nullable=False),
    sa.Column('bidding_fee', sa.Float(), nullable=False),
    sa.Column('commission_fee', sa.Float(), nullable=False),
    sa.Column('tax_fee', sa.Float(), nullable=False),
    sa.Column('daily_cost', sa.Float(), nullable=False),
    sa.Column('cumulative_cost', sa.Float(), nullable=False),
    sa.Column('cumulative_profit', sa.Float(), nullable=False),
    sa.Column('profit_rate', sa.Float(), nullable=False),
    sa.Column('invoice_amount', sa.Float(), nullable=False),
    sa.Column('output_value', sa.Float(), nullable=False),
    sa.Column('received_amount', sa.Float(), nullable=False),
    sa.Column('balance_amount', sa.Float(), nullable=False),
    sa.Column('receivable', sa.Float(), nullable=False),
    sa.Column('unsettled_value', sa.Float(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('reviewer', sa.String(length=50), nullable=True),
    sa.Column('registrant', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_record',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_design',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('key_personnel', sa.Text(), nullable=True),
    sa.Column('task_content', sa.Text(), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('subcontract',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('qualification', sa.String(length=100), nullable=True),
    sa.Column('company_scale', sa.String(length=100), nullable=True),
    sa.Column('contact_person', sa.String(length=50), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('settled_amount', sa.Float(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_detail',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('work_hours', sa.Float(), nullable=False),
    sa.Column('daily_rate', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('work_content', sa.Text(), nullable=True),
    sa.Column('is_leave', sa.Boolean(), nullable=False),
    sa.Column('leave_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['daily_execution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('execution_detail')
    op.drop_table('subcontract')
    op.drop_table('project_design')
    op.drop_table('payment_record')
    op.drop_table('daily_execution')
    op.drop_table('contract')
    op.drop_table('construction_task')
    op.drop_table('budget_item')
    op.drop_table('user')
    op.drop_table('project')
    op.drop_table('work_type')
    op.drop_table('employee')
    op.drop_table('attendance_type')
    # ### end Alembic commands ###
