"""add_personal_work_entry

Revision ID: e12e023c5c0e
Revises: dadaeb0b9da7
Create Date: 2026-05-14 19:07:25.974333
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e12e023c5c0e'
down_revision: Union[str, None] = 'dadaeb0b9da7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_work_entry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('work_hours', sa.Float(), nullable=False),
    sa.Column('work_content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_work_entry')
    # ### end Alembic commands ###
